name = "convincing_coffee_krill-5d5c"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "convincing_coffee_krill-5d5c_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "convincing_coffee_krill-5d5c.wasm"
command = "npm run build:release"
